# Generated by Django 4.2.15 on 2024-12-04 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("HighBP", models.BooleanField()),
                ("HighChol", models.BooleanField()),
                ("CholCheck", models.BooleanField()),
                ("BMI", models.FloatField()),
                ("Smoker", models.BooleanField()),
                ("Stroke", models.BooleanField()),
                ("HeartDiseaseorAttack", models.BooleanField()),
                ("PhysActivity", models.BooleanField()),
                ("Fruits", models.BooleanField()),
                ("Veggies", models.BooleanField()),
                ("HvyAlcoholConsump", models.BooleanField()),
                ("AnyHealthcare", models.BooleanField()),
                ("NoDocbcCost", models.BooleanField()),
                ("GenHlth", models.IntegerField()),
                ("MentHlth", models.IntegerField()),
                ("PhysHlth", models.IntegerField()),
                ("DiffWalk", models.BooleanField()),
                ("Sex", models.BooleanField()),
                ("Age", models.IntegerField()),
                ("Education", models.IntegerField()),
                ("Income", models.IntegerField()),
                ("Diabetes_binary", models.BooleanField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
